export const SET_USERINFO = 'SET_USERINFO'

export const SET_ORDERINFO = 'SET_ORDERINFO'

export const SET_CURRENTTABLE = 'SET_CURRENTTABLE'

export const SET_DININGLIST = 'SET_DININGLIST'

export const SET_GREENLIST = 'SET_GREENLIST'

export const SET_CURRENTDISCOUNTS = 'SET_CURRENTDISCOUNTS'

export const SET_MAXDISCOUNTS = 'SET_MAXDISCOUNTS'